#declare Bonds_Inc_Temp = version

#version 3.0


#declare Bond_H= texture {
        finish {Shiny }
        pigment {
         color White
         quick_color White
       }
}

#declare Bond_He= texture {
        finish {Shiny }
        pigment {
         color Orange
         quick_color Orange
       }
}

#declare Bond_Li= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Be= texture {
        finish {Shiny }
        pigment {
         color Orange
         quick_color Orange
       }
}

#declare Bond_B= texture {
        finish {Shiny }
        pigment {
         color Orange
         quick_color Orange
       }
}

#declare Bond_C= texture {
        finish {Shiny }
        pigment {
         color Gray75
         quick_color Gray75
       }
}

#declare Bond_N= texture {
        finish {Shiny }
        pigment {
         color Blue
         quick_color Blue
       }
}

#declare Bond_O= texture {
        finish {Shiny }
        pigment {
         color Red
         quick_color Red
       }
}

#declare Bond_F= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Ne= texture {
        finish {Shiny }
        pigment {
         color Orange
         quick_color Orange
       }
}

#declare Bond_Na= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Mg= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Al= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Si= texture {
        finish {Shiny }
        pigment {
         color Scarlet
         quick_color Scarlet
       }
}

#declare Bond_P= texture {
        finish {Shiny }
        pigment {
         color Yellow
         quick_color Yellow
       }
}

#declare Bond_S= texture {
        finish {Shiny }
        pigment {
         color Yellow
         quick_color Yellow
       }
}

#declare Bond_Cl= texture {
        finish {Shiny }
        pigment {
         color Orange
         quick_color Orange
       }
}

#declare Bond_Ar= texture {
        finish {Shiny }
        pigment {
         color Orange
         quick_color Orange
       }
}

#declare Bond_K= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Ca= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Sc= texture {
        finish {Shiny }
        pigment {
         color Scarlet
         quick_color Scarlet
       }
}

#declare Bond_Ti= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_V= texture {
        finish {Shiny }
        pigment {
         color BlueViolet
         quick_color BlueViolet
       }
}

#declare Bond_Cr= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Mn= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Fe= texture {
        finish {Shiny }
        pigment {
         color Scarlet
         quick_color Scarlet
       }
}

#declare Bond_Co= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ni= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Cu= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Zn= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ga= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ge= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_As= texture {
        finish {Shiny }
        pigment {
         color PaleGreen
         quick_color PaleGreen
       }
}

#declare Bond_Se= texture {
        finish {Shiny }
        pigment {
         color SpringGreen
         quick_color SpringGreen
       }
}

#declare Bond_Br= texture {
        finish {Shiny }
        pigment {
         color Green
         quick_color Green
       }
}

#declare Bond_Kr= texture {
        finish {Shiny }
        pigment {
         color Orange
         quick_color Orange
       }
}

#declare Bond_Rb= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Sr= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Y= texture {
        finish {Shiny }
        pigment {
         color Yellow
         quick_color Yellow
       }
}

#declare Bond_Zr= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Nb= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Mo= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Tc= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ru= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Rh= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Pd= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Cd= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_In= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Sn= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Sb= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Te= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_I= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Xe= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Cs= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ba= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_La= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ce= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Pr= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Nd= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Pm= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Sm= texture {
        finish {Shiny }
        pigment {
         color DarkGreen
         quick_color DarkGreen
       }
}

#declare Bond_Eu= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Gd= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Tb= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Dy= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ho= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Er= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Tm= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Yb= texture {
        finish {Shiny }
        pigment {
         color Maroon
         quick_color Maroon
       }
}

#declare Bond_Lu= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Hf= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ta= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Wb= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Re= texture {
        finish {Shiny }
        pigment {
         color Red
         quick_color Red
       }
}

#declare Bond_Os= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Ir= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Pt= texture {
        finish {Shiny }
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
}

#declare Bond_Au=  texture {Gold_Texture}


#declare Bond_Hg= 
       texture {Brass_Texture}


#declare Bond_Tl= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Pb= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Bi= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Po= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_At= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Rn= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Fr= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Ra= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Ac= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Th= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Pa= texture {
        pigment {
         color PaleGreen
         quick_color PaleGreen
       }
  }

#declare Bond_U= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Np= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Pu= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Am= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Cm= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Bk= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Cf= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Es= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Fm= texture {
	pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Md= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_No= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Lr= texture {
        pigment {
         color MidnightBlue
         quick_color MidnightBlue
       }
  }

#declare Bond_Ag= 
       texture {Silver_Texture}

#version Bonds_Inc_Temp



